### ISSUE TITLE
How do i replace the images with new images?

### ISSUE THREAD

**Issue by Fireballion** [freshsomebody/move-mirror-clone#2]
Hi. I am wondering how to make this recognise different pictures other than ones in the assets folder. How do i go about doing this?

Regards,

**Comment by freshsomebody** [comment]
Hi @Fireballion ,thank you for your feedback.
Indeed, it should be a common question, and I just added the instruction in README.md
https://github.com/freshsomebody/move-mirror-clone#add-replace-mirror-images
