### ISSUE TITLE
The http://localhost:3000/debug/mirrorImages doesn’t work for me 

### ISSUE THREAD

**Issue by Fireballion** [freshsomebody/move-mirror-clone#3]
Hi.
I cd into the directory of th project and run npm install then I run npm run dev but I can’t use the http://localhost:3000/debug/mirrorImages as it says some stuff about a DS Store which I have no idea how to rectify. Please help out as I am trying to use different set of images with this. Thank you.

**Comment by freshsomebody** [comment]
Hi @Fireballion , thank you for your report.
May I ask what your working environment is, including:
- OS
- Node version

so I can reproduce the problem?

**Comment by Fireballion** [comment]
Sure thanks for replying so fast. I am using the latest version of node and macOS

**Comment by Fireballion** [comment]
It says 'Nuxt Server Error Cannot find module './.DS_Store''

**Comment by Fireballion** [comment]
@freshsomebody It also gives an error message for:
webpack:/assets/images/mirror-poses sync ^\.\/.*$:35:  webpackContextResolve
webpack:/assets/images/mirror-poses sync ^\.\/.*$:30: webpackContext
pages/debug/MirrorImages.js:901:94 
pages/debug/MirrorImages.vue:32: Proxy.render

**Comment by Fireballion** [comment]
I am quite new to node.js and nuxt so any guidance would be much appreciated

**Comment by Fireballion** [comment]
Actually i just fixed it

**Comment by Fireballion** [comment]
Thanks so much for your help
It must have been me then i just had to install the project again and it worked like a charm.

**Comment by freshsomebody** [comment]
Hi @Fireballion 
Thank you very much for the feedback!
I haven't successfully reproduced the problem, but it is great to know you had solved it.

I am closing this issue for now, but please feel free to re-open or create a new issue if you got any problem.

**Comment by Fireballion** [comment]
Hi. I have tried replacing the images but the issue with the ./.DSStore persists, are there some limits on the image(like resolution and colour profile)?

**Comment by Fireballion** [comment]
@freshsomebody I think if you try using some different images entirely you might be able to see what i am talking about

**Comment by Fireballion** [comment]
Actually I myself seem to have fixed it @freshsomebody 
Can i make an ammendement to the add process?

**Comment by Fireballion** [comment]
in the README.md?

**Comment by freshsomebody** [comment]
Hi @Fireballion , thank you very much to keep tracking this issue.
Though it is not completely the same with yours, I found there may be an error if your delete all of the images after you start the dev server.

> Actually I myself seem to have fixed it @freshsomebody
> Can i make an ammendement to the add process?
> in the README.md?

Yes, it is great if you would like to share how you troubleshot this problem. Maybe you can write your solution here first. After we better address the issue, you or we can make a PR amend it.

**Comment by Fireballion** [comment]
Hi @freshsomebody , basically for me i had to find images of 72*72 resolution with the sRGB IEC61966-2.1 colour profile. Also I had to then just terminate and rerun the terminal

**Comment by freshsomebody** [comment]
Hi @Fireballion , thank you for the information! I didn't know that the color profile may have problems before, so it is a cool fact to me. It should be the compatibility issue of browsers and/or devices to correctly recognize the images.

May I ask what color profile does not work for you? I tried several ones, but I didn't get the errors.
