### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by PrashantSaikia** [freshsomebody/move-mirror-clone#4]
In the `Build Setup` section, the first step you mention is `npm run install`. But where is this `install` file located? I get this error:

```
npm ERR! missing script: install

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2020-08-04T08_50_51_475Z-debug.log
```

I searched through every folder in your repo, but can't find the `install` file anywhere.

**Comment by freshsomebody** [comment]
Hi @PrashantSaikia , thank you for reporting!
Sorry I made a mistake of installation script in the README. I will fix it right away.

The script should be `npm install` (without `run`).
Execute `npm install` at its root folder (the same level with package.json), and it should work.
